### ISSUE TITLE
In Class Deployment Feedback

### ISSUE THREAD

**Issue by sgullion** [BVCOG-Contract-Management/BVGOG-Contract-Manager#91]
Issues with Local Deployment and Testing
When attempting to deploy locally, we ran into an issue when we tried to run “bundle install”. The code required Ruby 3.2.0, but we had Ruby 3.2.2 installed. We were able to get around this by changing the version of Ruby required in the gemfile as suggested by a member of your team, and this allowed us to run “rails s” to deploy locally. However, when attempting to run your cucumber and rspec tests, neither worked, which may have been caused by switching the Ruby version earlier. The errors produced were
“ActiveSupport::MessageEncryptor::InvalidMessage(ActiveSupport::MessageEncryptor::InvalidMessage)” 
and 
“Failure/Error: require_relative '../config/environment' 
ActiveSupport::MessageEncryptor::InvalidMessage:
  ActiveSupport::MessageEncryptor::InvalidMessage
# ./config/environment.rb:7:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `require_relative'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# ./spec/helpers/contract_documents_helper_spec.rb:3:in `<top (required)>'
# ------------------
# --- Caused by: ---
# OpenSSL::Cipher::CipherError:
#   ./config/environment.rb:7:in `<top (required)>'
” 
respectively.

Issues with Deployment to Heroku
The first issue we ran into when trying to deploy to Heroku was logging in to Heroku using “heroku login -i”. Trying to log in using an email and password didn’t work. Instead, we needed to use an API key in place of a password. This was a minor issue, but something you might want to address in your instructions. The second issue we ran into was with “heroku create bvcog”. We were unable to name our app bvcog because that name was already taken. Again, this was also a minor issue, as we just had to choose a different name in order to move forward. The biggest issue we ran into was with “EDITOR=vim rails credentials:edit”. We were attempting to deploy this code on a Windows machine, and attempting to run this command in Window’s command prompt and powershell both gave the error “'EDITOR' is not recognized as an internal or external command, operable program or batch file.” Eventually, we attempted to run it in a git bash terminal, in which the command was recognized, but it gave an error about Ruby 3.2.0 being required when the machine had 3.2.2 installed. Even if this step would have worked, we would not have been able to proceed any further because this is where the deployment instructions end. Please include instructions detailing the full process of deployment in the future.

Additional Concern:
There does not appear to be a way to contact team members in the README file.

**Comment by sgullion** [comment]
It seems Github automatically formatted the error message in as strange way. Sorry, that was not meant to be that big.
